typography_spectrum: 0.9956672894768417
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.04143374809063971
  lightness: 0.21378804929554462
  saturation: 0.3860954998526722
  rhythmicContrast: 0.31812687194906175
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6338228634558618
analytics:
  google: null
  facebook: null
  twitter: null
name: buh
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: This is the best webpage EVER!
purpose: []
